export const routes = {
  home: "/",
  watchLists: "/watch-lists",
  following: "/following",
  followTargets: "/follow-targets",
  mutualFollowers: "/mutual-followers",
  targetAchieved: "/target-achieved",
  analytics: "/analytics",
  settings: "/settings",
  profile: "/profile",
  notifications: "/notifications",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  unauthorized: "/unauthorized",
} as const;
